import { Inter } from "next/font/google";
import "./globals.css";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import Header from "../components/header";
import { UserProvider } from "./context/userContext";
import "@uploadthing/react/styles.css";
import { ourFileRouter } from "../app/api/uploadthing/core";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      </head>
      <body className={inter.className}>
        <Providers>
          <UserProvider>
            <Header />
            {children}
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
